### ISSUE TITLE
At startup, "job-lb-policy-nearest-*" pods sometimes fail the first few tries

### ISSUE THREAD

**Issue by thebithead** [nuodb/nuodb-helm-charts#85]
K8s v1.15.5 running in minikube.

```
tgates@tgu19:~/nuodb/nuodb-helm-operator/deploy$ kc get pods 
NAME                                   READY   STATUS      RESTARTS   AGE
example-admin-nuodb-cluster0-0         1/1     Running     0          98s
job-lb-policy-nearest-6wlwc            0/1     Error       0          73s
job-lb-policy-nearest-rgnjx            0/1     Error       0          98s
job-lb-policy-nearest-xxsl9            0/1     Completed   0          63s
nuodb-helm-operator-7cf7c858d5-462mj   1/1     Running     0          2m58s
tgates@tgu19:~/nuodb/nuodb-helm-operator/deploy$ 
```

One of the failed tries:

```
tgates@tgu19:~/nuodb/nuodb-helm-operator/deploy$ kc logs job-lb-policy-nearest-rgnjx
Unable to connect to https://nuodb.nuodb.svc:8888: HTTPSConnectionPool(host='nuodb.nuodb.svc', port=8888): Max retries exceeded with url: /api/1/databases/loadBalancerPolicy/nearest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7efd2d1ad410>: Failed to establish a new connection: [Errno -2] Name or service not known',))
tgates@tgu19:~/nuodb/nuodb-helm-operator/deploy$
```

Maybe there is some kind of race condition before the service is created?

**Comment by butson** [comment]
yes there is a race condition this has been known since the job was
created.   I thought I had addressed in the last 6 months with an init
container.

But it does not really matter.  The end result is the same and no damage
was done.

Dirk Butson

Principal Consultant
www.nuodb.com

p: +1 (617) 500-0001 <http://www.nuodb.com/company/office-locations>
t: @nuodb
<https://twitter.com/nuodb>l: linkedin.com/company/NUODB
<https://www.linkedin.com/company/NUODB>

The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Comment by adriansuarez** [comment]
Now that the Admin can inspect Kubernetes state, I think it makes more sense to perform this sort of configuration using Kubernetes labels (e.g. on the Admin StatefulSet or on the TE Deployments), which an Admin process can detect and apply to KV-store itself. There have been improvements to the load-balancer DSL to allow default policies to be registered, either for a particular database or globally, that do not require SQL clients to specify the `LBPolicy` connection property.

We could encode the global default policy as labels for the Admin StatefulSet and the database default policy as labels for the TE Deployments (TEs may also have NuoDB process labels that are used in the policy, so it makes sense to define the policy and the process labeling in the same file).

Here is my proposal...

For the Admin StatefulSet:
```yaml
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  labels:
    loadBalancerPolicyDefault:  {{ .Values.admin.lbQuery | quote }}
...
```

For the TE Deployment:
```yaml
apiVersion: "apps/v1"
kind: Deployment
metadata:
  labels:
    loadBalancerPolicyDefault:  {{ .Values.database.lbQuery | quote }}
...
```

@vegichan , @acabrele : Thoughts?

**Comment by butson** [comment]
I think the policy defined by default should just be the global default by default.  So it would not be something you define on the TE.

Also do you want to be checking and updating for every TE that is started.

Maybe having an initcontainer in admin that can execute scripts on startup.  You can inspect for onfigmaps labeled in a certain manner which contains the script to execute.  So you could easily add config maps.  You can also make it dynamic so that it polls and mounts new config maps.  The trouble is you only want one pod to execute script.  While all would mount them.  See the grafana helm chart for an example of dynamically mounting configmaps based upon label.

**Comment by adriansuarez** [comment]
@butson : What I'm referring to is that the Admin will soon (already on master) have the ability to detect changes to K8s objects (Pods, PVCs, StatefulSets, Deployments). So the Admin would detect the global default policy immediately since the Admin StatefulSet would exist before any Admin process is started, and it would detect the database default in the TE Deployment at the time that the Deployment is created (or the whenever the label is updated), not every time that a TE Pod is created.
